insert into public.activities (city_id, title, description, type, duration_minutes, cost_usd, image_url)
select c.id, v.title, v.descr, v.atype, v.dur, v.cost, 'https://picsum.photos/seed/' || v.slug || '/900/600'
from (values
('Paris','Louvre Museum','Wings of antiquities and Renaissance painting; book a timed entry.','Culture',180,22,'act-louvre'),
('Paris','Eiffel Tower Summit','Lift to the second floor, then the summit for the river panorama.','Sightseeing',120,29,'act-eiffel'),
('Paris','Le Marais Food Walk','Falafel, fromagerie stops and a bakery finish through the old quarter.','Food',150,45,'act-marais'),
('Paris','Seine Evening Cruise','One hour on the water as the bridges light up.','Entertainment',60,18,'act-seine'),
('Paris','Musee d''Orsay','Impressionist collection inside a converted railway station.','Culture',120,16,'act-orsay'),
('Paris','Montmartre Sunset Climb','Steps up to Sacre-Coeur for the city''s best free view.','Nature',90,0,'act-montmartre'),
('London','British Museum','Free entry, two millennia of collections; pick three galleries.','Culture',150,0,'act-britishmuseum'),
('London','Tower of London','Crown jewels, ravens and Norman fortress walls.','Sightseeing',150,38,'act-tower'),
('London','Borough Market Tasting','Cheese, oysters and coffee under the railway arches.','Food',90,35,'act-borough'),
('London','West End Show','Evening theatre in Covent Garden.','Entertainment',165,75,'act-westend'),
('London','Hampstead Heath Walk','Ponds, meadows and the Parliament Hill skyline.','Nature',120,0,'act-hampstead'),
('Tokyo','Senso-ji and Asakusa','Temple gate, incense and Nakamise shopping street.','Culture',120,0,'act-sensoji'),
('Tokyo','Tsukiji Outer Market','Tamagoyaki, tuna and knife shops early in the morning.','Food',105,30,'act-tsukiji'),
('Tokyo','Shibuya and Harajuku','Crossing, backstreets and Takeshita-dori.','Shopping',180,25,'act-shibuya'),
('Tokyo','TeamLab Planets','Immersive digital art you walk through barefoot.','Entertainment',90,28,'act-teamlab'),
('Tokyo','Shinjuku Gyoen','Landscaped gardens for a quiet reset mid-trip.','Nature',90,4,'act-gyoen'),
('Tokyo','Mount Takao Hike','Cable car and forest trail an hour from the centre.','Adventure',300,20,'act-takao'),
('Kyoto','Fushimi Inari Shrine','Thousands of vermilion gates up the mountainside.','Culture',150,0,'act-fushimi'),
('Kyoto','Arashiyama Bamboo Grove','Early morning walk before the paths fill.','Nature',90,0,'act-arashiyama'),
('Kyoto','Kaiseki Dinner','Multi-course seasonal tasting menu.','Food',120,95,'act-kaiseki'),
('Kyoto','Nishiki Market','Covered market of pickles, tofu and sweets.','Food',75,20,'act-nishiki'),
('Kyoto','Kinkaku-ji','The golden pavilion above its reflecting pond.','Sightseeing',75,5,'act-kinkakuji'),
('Dubai','Burj Khalifa At The Top','Observation decks on levels 124 and 125.','Sightseeing',90,44,'act-burj'),
('Dubai','Desert Dune Safari','Afternoon dune drive, camels and a camp dinner.','Adventure',300,70,'act-desert'),
('Dubai','Old Dubai Souks','Gold and spice souks with an abra crossing.','Shopping',120,10,'act-souk'),
('Dubai','Dubai Marina Dhow Dinner','Traditional boat, modern skyline.','Food',120,55,'act-dhow'),
('Dubai','Jumeirah Beach Morning','Public beach with a view of the sail hotel.','Nature',120,0,'act-jumeirah'),
('Singapore','Gardens by the Bay','Supertrees, cloud forest dome and the light show.','Nature',150,22,'act-gardens'),
('Singapore','Maxwell Hawker Centre','Chicken rice, laksa and kopi at the source.','Food',75,12,'act-maxwell'),
('Singapore','Sentosa Day Trip','Beaches, cable car and boardwalk.','Entertainment',300,35,'act-sentosa'),
('Singapore','Peranakan Katong Walk','Shophouse colour and laksa in the east.','Culture',120,15,'act-katong'),
('Singapore','Orchard Road','Air-conditioned shopping mile.','Shopping',150,0,'act-orchard'),
('Bali','Tegallalang Rice Terraces','Layered green valley north of Ubud.','Nature',120,5,'act-tegallalang'),
('Bali','Uluwatu Temple Sunset','Cliff temple with the kecak fire dance.','Culture',150,12,'act-uluwatu'),
('Bali','Canggu Surf Lesson','Two hours with a board and instructor.','Adventure',120,30,'act-surf'),
('Bali','Ubud Market and Palace','Crafts, textiles and the royal courtyard.','Shopping',105,10,'act-ubud'),
('Bali','Mount Batur Sunrise Trek','Pre-dawn climb to a volcanic ridge.','Adventure',360,55,'act-batur'),
('Barcelona','Sagrada Familia','Gaudi''s basilica; timed entry with tower option.','Culture',105,33,'act-sagrada'),
('Barcelona','Park Guell','Mosaic terraces above the city.','Sightseeing',105,12,'act-guell'),
('Barcelona','Gothic Quarter Tapas','Small plates and vermouth through narrow lanes.','Food',150,50,'act-tapas'),
('Barcelona','Barceloneta Beach','Afternoon swim and a seafront walk.','Nature',150,0,'act-barceloneta'),
('Barcelona','Montjuic Cable Car','Ride up for the harbour view and the castle.','Adventure',120,15,'act-montjuic'),
('Rome','Colosseum and Forum','Combined ticket for the arena and Roman Forum.','Culture',180,24,'act-colosseum'),
('Rome','Vatican Museums','Galleries ending at the Sistine Chapel.','Culture',180,27,'act-vatican'),
('Rome','Trastevere Food Crawl','Cacio e pepe, suppli and a gelato finish.','Food',150,48,'act-trastevere'),
('Rome','Pantheon and Piazzas','Free-entry dome, then Navona and the Trevi Fountain.','Sightseeing',120,0,'act-pantheon'),
('Rome','Villa Borghese Gardens','Rented bikes and a terrace view over the city.','Nature',120,10,'act-borghese'),
('New York','The Met','Encyclopedic museum on the edge of Central Park.','Culture',180,30,'act-met'),
('New York','Top of the Rock','Observation deck facing the Empire State Building.','Sightseeing',90,40,'act-topoftherock'),
('New York','Brooklyn Bridge Walk','Cross at golden hour into DUMBO.','Nature',90,0,'act-brooklynbridge'),
('New York','Broadway Show','Evening performance in the theatre district.','Entertainment',165,120,'act-broadway'),
('New York','Chelsea Market and High Line','Food hall, then the elevated park.','Food',150,35,'act-highline'),
('Mumbai','Gateway of India','Harbour arch and the Colaba seafront.','Sightseeing',75,0,'act-gateway'),
('Mumbai','Elephanta Caves','Ferry out to rock-cut island temples.','Culture',270,15,'act-elephanta'),
('Mumbai','Mohammed Ali Road Food Walk','Kebabs, malpua and late-night street stalls.','Food',150,14,'act-mohammedali'),
('Mumbai','Marine Drive Sunset','The queen''s necklace curve at dusk.','Nature',75,0,'act-marinedrive'),
('Mumbai','Dharavi Community Tour','Guided walk with a local social enterprise.','Culture',150,20,'act-dharavi'),
('Delhi','Red Fort','Mughal sandstone fortress in Old Delhi.','Culture',120,8,'act-redfort'),
('Delhi','Humayun''s Tomb','Garden tomb that prefigured the Taj Mahal.','Sightseeing',90,7,'act-humayun'),
('Delhi','Chandni Chowk Food Walk','Parathas, jalebi and chaat by rickshaw.','Food',150,12,'act-chandni'),
('Delhi','Qutub Minar','Twelfth-century minaret and ruined complex.','Sightseeing',75,7,'act-qutub'),
('Delhi','Lodhi Art District','Street murals across a quiet colony.','Culture',90,0,'act-lodhi'),
('Delhi','India Gate Evening','War memorial and lawns after dark.','Sightseeing',60,0,'act-indiagate'),
('Jaipur','Amber Fort','Hilltop fort with mirrored halls.','Culture',150,12,'act-amber'),
('Jaipur','City Palace and Jantar Mantar','Royal courtyards and the stone observatory.','Sightseeing',150,15,'act-citypalace'),
('Jaipur','Block Printing Workshop','Hands-on session with local artisans.','Culture',120,25,'act-blockprint'),
('Jaipur','Rajasthani Thali Dinner','Dal baati churma and a full brass thali.','Food',90,14,'act-thali'),
('Jaipur','Nahargarh Sunset Drive','Ridge fort above the pink city.','Nature',120,6,'act-nahargarh'),
('Udaipur','City Palace Udaipur','Lakeside palace complex and museum.','Culture',120,12,'act-udaipalace'),
('Udaipur','Lake Pichola Boat Ride','Sunset crossing past Jag Mandir.','Sightseeing',60,14,'act-pichola'),
('Udaipur','Monsoon Palace Viewpoint','Hilltop palace over the lakes.','Nature',105,8,'act-monsoon'),
('Udaipur','Rooftop Rajasthani Dinner','Folk music with a palace view.','Food',105,18,'act-udaidinner'),
('Udaipur','Shilpgram Crafts Village','Regional crafts and live performance.','Shopping',105,5,'act-shilpgram'),
('Bangkok','Grand Palace and Wat Phra Kaew','Gilded royal compound and the Emerald Buddha.','Culture',150,15,'act-grandpalace'),
('Bangkok','Chao Phraya Ferry Hop','Public boat between riverside temples.','Sightseeing',90,3,'act-chaophraya'),
('Bangkok','Chinatown Street Food','Yaowarat noodles, satay and mango sticky rice.','Food',150,15,'act-yaowarat'),
('Bangkok','Thai Cooking Class','Market shop then four dishes to cook.','Food',210,40,'act-thaicooking'),
('Bangkok','Chatuchak Weekend Market','Thousands of stalls; go early.','Shopping',180,10,'act-chatuchak'),
('Istanbul','Hagia Sophia','Byzantine dome turned mosque and monument.','Culture',90,25,'act-hagiasophia'),
('Istanbul','Topkapi Palace','Ottoman court, treasury and harem quarters.','Culture',150,22,'act-topkapi'),
('Istanbul','Bosphorus Ferry','Cross to the Asian side for tea and fish.','Sightseeing',120,6,'act-bosphorus'),
('Istanbul','Grand Bazaar','Covered market of carpets, lamps and spice.','Shopping',120,10,'act-grandbazaar'),
('Istanbul','Kadikoy Food Walk','Meze, simit and Turkish coffee.','Food',150,32,'act-kadikoy')
) as v(city, title, descr, atype, dur, cost, slug)
join public.cities c on c.name = v.city;